# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global.parameters]
stack_name = "newrelic-securitylake-s3-processor"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "newrelic-securitylake-s3-processor"
region = "us-west-2"
parameter_overrides = "SecurityLakeSubscriberRoleArn=\"arn:aws:iam::083472518088:role/AmazonSecurityLake-ab0cf0f4-7569-4e80-9aea-09400e3c3b1f\" SecurityLakeSQSArn=\"arn:aws:sqs:us-west-2:083472518088:AmazonSecurityLake-ab0cf0f4-7569-4e80-9aea-09400e3c3b1f-Main-Queue\" ExternalID=\"anuj-cross-account\" NRLicenseKey=\"74dbedf8a2edae0e489977ef10df7d55FFFFNRAL\""
image_repositories = []

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
